import type { ServiceContractFormData } from '../types/serviceContract';

/** Return YYYY-MM-DD in the user's local timezone (not UTC) */
const today = () => new Date().toLocaleDateString('en-CA');

export const SERVICE_CONTRACT_INITIAL_DATA: ServiceContractFormData = {
  serviceAgreement: {
    date: today(),
    customerInfo: {
      firstName: '',
      lastName: '',
      address: '',
      phone: '',
      ssnLast4: '',
      dateOfBirth: '',
      startOfCareDate: '',
      daysPerWeek: '',
      hoursPerDay: '',
      liveIn: '',
    },
    paymentTerms: {
      rateType: '',
      hourlyRateOption: '',
      customHourlyRate: '',
      liveInRate: '',
      holidayRatesApply: true,
    },
    levelOfService: {
      cna: false,
      chha: false,
      other: false,
      otherText: '',
    },
    methodOfPayment: {
      check: false,
      creditCard: false,
      achEft: false,
      longTermCareInsurance: false,
      insurancePolicyName: '',
      insurancePolicyNumber: '',
      insuranceContactName: '',
      insuranceContactAddress: '',
      insuranceContactPhone: '',
      insuranceContactRelationship: '',
    },
    contactPerson: {
      name: '',
      address: '',
      phone: '',
      relationship: '',
    },
    billingPerson: {
      name: '',
      address: '',
      phone: '',
      relationship: '',
    },
    services: {
      selfAdminMeds: false,
      personalCare: false,
      homemaking: false,
      transportation: false,
      companionship: false,
      respiteCare: false,
      otherNonSkilled: false,
      otherNonSkilledText: '',
    },
    frequency: {
      monday: false,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: false,
      saturday: false,
      sunday: false,
      orAsRequested: false,
      duration: '',
      startTime: '',
      startAmPm: '',
      endTime: '',
      endAmPm: '',
      available24x7: false,
      overnight: false,
      liveIn: false,
      daySchedules: {},
    },
    assignedCaregiver: '',
    serviceDeposit: '',
    clientSignature: '',
    clientSignatureMeta: null,
    clientPrintName: '',
    signerIsRepresentative: false,
    representativeName: '',
    representativeRelationship: '',
    ehcRepName: '',
    ehcRepSignature: '',
    ehcRepSignatureMeta: null,
  },

  termsConditions: {
    nonSolicitationInitial: '',
    termsOfPaymentInitial: '',
    cardSurchargeInitial: '',
    terminationInitial: '',
    authorizationConsentInitial: '',
    relatedDocumentsInitial: '',
  },

  consumerRights: {
    consumerName: '',
    acknowledgeSignature: '',
    acknowledgeSignatureMeta: null,
    acknowledgeDate: today(),
    responsiblePartyRelationship: '',
  },

  directCareWorker: {
    consumerName: '',
    employeeOfEhcInitial: '',
    registryNotEmployeeInitial: '',
    liabilityInsuranceInitial: '',
    consumerSignature: '',
    consumerSignatureMeta: null,
    agencyRepSignature: '',
    agencyRepSignatureMeta: null,
    date: today(),
  },

  transportationRequest: {
    consumerName: '',
    declined: false,
    vehicleChoice: '',
    employeeNames: '',
    clientSignature: '',
    clientSignatureMeta: null,
    clientRelationship: '',
    ehcRepName: '',
    ehcRepTitle: '',
    ehcRepSignature: '',
    ehcRepSignatureMeta: null,
    date: today(),
  },

  customerPacket: {
    consumerName: '',
    acknowledgeHipaa: { checked: false, timestamp: '' },
    acknowledgeHiringStandards: { checked: false, timestamp: '' },
    acknowledgeCaregiverIntro: { checked: false, timestamp: '' },
    acknowledgeComplaintProcedures: { checked: false, timestamp: '' },
    acknowledgeSatisfactionSurvey: { checked: false, timestamp: '' },
    acknowledgeSignature: '',
    acknowledgeSignatureMeta: null,
    acknowledgeDate: today(),
  },
};
