import type { AssessmentFormData } from '../types/forms';

export const INITIAL_DATA: AssessmentFormData = {
  clientHelpList: {
    clientName: '',
    dateOfBirth: '',
    clientAddress: '',
    goals: '',
    clientPhone: '',
    referralAgency: '',
    date: new Date().toISOString().split('T')[0],
    emergencyContacts: [
      { name: '', relationship: '', address: '', phone1: '', phone2: '' },
      { name: '', relationship: '', address: '', phone1: '', phone2: '' },
      { name: '', relationship: '', address: '', phone1: '', phone2: '' },
    ],
    doctors: [
      { name: '', type: '', phone: '' },
      { name: '', type: '', phone: '' },
      { name: '', type: '', phone: '' },
    ],
    hospitalPreference1: '',
    hospitalPreference2: '',
    neighborName: '',
    neighborPhone: '',
    neighborHasKeys: '',
    healthRecentlyEvents: '',
  },
  clientHistory: {
    clientName: '',
    date: new Date().toISOString().split('T')[0],
    age: '',
    assessmentReason: '',
    reAssessmentReasons: [],
    reAssessmentOtherReason: '',
    servicesPerWeek: '',
    overnight: false,
    liveIn: false,
    serviceStartDate: '',
    preferredTimes: [
      { from: '', to: '' },
      { from: '', to: '' },
      { from: '', to: '' },
    ],
    primaryDiagnosis: '',
    healthHistory: [],
    lastFallDate: '',
    hospitalizations: '',
    recentSurgery: '',
    recentHipSurgery: '',
    recentHipSurgeryDate: '',
    smoker: '',
    oxygenInHome: '',
    recentInfections: '',
    otherProviders: [
      { agencyName: '', typeOfAgency: '', phone: '', address: '', email: '' },
    ],
    advanceDirective: '',
    visionImpaired: false,
    visionBothEyes: false,
    visionRightOnly: false,
    visionLeftOnly: false,
    visionGlasses: false,
    visionContacts: false,
    hearingAids: false,
    hearingBothEars: false,
    hearingRightEar: false,
    hearingLeftEar: false,
    hearingSignLanguage: false,
    hearingTablet: false,
    speechImpaired: '',
    primaryLanguage: '',
    primaryLanguageOther: '',
    understandsEnglish: '',
    diet: [],
    dietOther: '',
    drugAllergies: '',
    foodAllergies: '',
    livesAlone: '',
    peopleInHome: '',
    whoAreThey: '',
    whenOthersHome: '',
    pets: '',
    petKind: '',
    petCount: '',
  },
  clientAssessment: {
    clientName: '',
    date: new Date().toISOString().split('T')[0],
    assessmentType: '',
    revisedDate: '',
    bathing: [],
    dressing: [],
    hairCare: [],
    teethAndGums: [],
    shaving: [],
    mobility: [],
    falls: [],
    mobilityAids: [],
    nutritionHydration: [],
    bedRails: [],
    hearingAids: [],
    toileting: [],
    medicationReminder: [],
    exerciseReminders: [],
    housekeeping: [],
    transportation: [],
  },
  homeSafetyChecklist: {
    clientName: '',
    date: new Date().toISOString().split('T')[0],
    clientAddress: '',
    entrance: {},
    general: {},
    medications: {},
    medicalEquipment: {},
    livingAreas: {},
    bathroom: {},
    bedroom: {},
    kitchen: {},
    lighting: {},
    security: {},
    ancillaryServices: {},
    comments: '',
    itemsNeedingAttention: '',
    signerName: '',
    ehcStaffName: '',
    clientSignature: '',
    representativeSignature: '',
    representativeName: '',
  },
  medicationList: {
    clientName: '',
    date: new Date().toISOString().split('T')[0],
    clientAddress: '',
    age: '',
    medicationAllergies: '',
    medications: [
      { name: '', dosage: '', frequency: '', route: '', updates: '' },
    ],
    noMedications: false,
  },
  consent: {
    clientName: '',
    date: new Date().toISOString().split('T')[0],
    clientAddress: '',
    age: '',
    signerName: '',
    ehcStaffName: '',
    hipaaSignature: '',
    hipaaSignatureDate: new Date().toISOString().split('T')[0],
    benefitsSignature: '',
    benefitsSignatureDate: new Date().toISOString().split('T')[0],
  },
};
