import type { AssessmentFormData } from '../types/forms';

export const INITIAL_DATA: AssessmentFormData = {
  clientHelpList: {
    clientName: '',
    dateOfBirth: '',
    clientAddress: '',
    goals: '',
    clientPhone: '',
    referralAgency: '',
    date: new Date().toLocaleDateString('en-CA'),
    emergencyContacts: [
      { name: '', relationship: '', address: '', phone1: '', phone2: '', email: '' },
    ],
    doctors: [
      { name: '', type: '', phone: '' },
    ],
    hospitals: [
      { name: '' },
    ],
    neighbors: [
      { name: '', phone: '', hasKeys: '' },
    ],
    healthRecentlyEvents: '',
  },
  clientHistory: {
    clientName: '',
    date: new Date().toLocaleDateString('en-CA'),
    age: '',
    clientAddress: '',
    assessmentReason: '',
    reAssessmentReasons: [],
    reAssessmentOtherReason: '',
    servicesPerWeek: '',
    overnight: false,
    liveIn: false,
    is24x7: false,
    serviceStartDate: '',
    serviceDays: [],
    daySchedules: {},
    primaryDiagnosis: '',
    healthHistory: [],
    lastFallDate: '',
    hospitalizations: '',
    recentSurgery: '',
    recentHipSurgery: '',
    recentHipSurgeryDate: '',
    smoker: '',
    smokerNotes: '',
    oxygenInHome: '',
    recentInfections: '',
    otherProviders: [
      { agencyName: '', typeOfAgency: '', phone: '', address: '', email: '' },
    ],
    advanceDirective: '',
    visionImpaired: false,
    visionBothEyes: false,
    visionRightOnly: false,
    visionLeftOnly: false,
    visionGlasses: false,
    visionContacts: false,
    hearingAids: false,
    hearingBothEars: false,
    hearingRightEar: false,
    hearingLeftEar: false,
    hearingSignLanguage: false,
    hearingTablet: false,
    speechImpaired: '',
    primaryLanguage: '',
    primaryLanguageOther: '',
    understandsEnglish: '',
    diet: [],
    dietOther: '',
    drugAllergies: '',
    foodAllergies: '',
    livesAlone: '',
    peopleInHome: '',
    whoAreThey: '',
    whenOthersHome: '',
    pets: '',
    petKind: '',
    petCount: '',
    ehcStaffName: '',
    ehcRepSignature: '',
    ehcRepSignatureMeta: null,
  },
  clientAssessment: {
    clientName: '',
    date: new Date().toLocaleDateString('en-CA'),
    age: '',
    clientAddress: '',
    assessmentType: '',
    revisedDate: '',
    bathing: [],
    dressing: [],
    hairCare: [],
    teethAndGums: [],
    shaving: [],
    mobility: [],
    falls: [],
    mobilityAids: [],
    nutritionHydration: [],
    bedRails: [],
    hearingAids: [],
    toileting: [],
    medicationReminder: [],
    exerciseReminders: [],
    housekeeping: [],
    transportation: [],
    ehcStaffName: '',
    ehcRepSignature: '',
    ehcRepSignatureMeta: null,
  },
  homeSafetyChecklist: {
    clientName: '',
    date: new Date().toLocaleDateString('en-CA'),
    clientAddress: '',
    age: '',
    entrance: {},
    general: {},
    medications: {},
    medicalEquipment: {},
    livingAreas: {},
    bathroom: {},
    bedroom: {},
    kitchen: {},
    lighting: {},
    security: {},
    ancillaryServices: {},
    comments: '',
    itemsNeedingAttention: '',
    signerName: '',
    ehcStaffName: '',
    clientSignature: '',
    clientSignatureMeta: null,
    representativeSignature: '',
    representativeSignatureMeta: null,
  },
  medicationList: {
    clientName: '',
    date: new Date().toLocaleDateString('en-CA'),
    clientAddress: '',
    age: '',
    medicationAllergies: '',
    medications: [
      { name: '', dosage: '', frequency: '', route: '', updates: '' },
    ],
    noMedications: false,
  },
  consent: {
    clientName: '',
    date: new Date().toLocaleDateString('en-CA'),
    clientAddress: '',
    age: '',
    consentTreatment: { checked: false, timestamp: '' },
    consentInfoSharing: { checked: false, timestamp: '' },
    consentElectronicRecords: { checked: false, timestamp: '' },
    consentDataRetention: { checked: false, timestamp: '' },
    signerName: '',
    hipaaSignature: '',
    hipaaSignatureMeta: null,
    hipaaSignatureDate: new Date().toLocaleDateString('en-CA'),
  },
  staffNotes: {
    clientHelpList: '',
    clientHistory: '',
    clientAssessment: '',
    homeSafetyChecklist: '',
    medicationList: '',
    consent: '',
  },
};
